services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: dottoe
    platform: linux/amd64
    ports:
      - "3308:3306" # This binds MySQL port 3306 to host port 3308
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

volumes:
  db_data:
