CREATE TABLE `profiles` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `first_name` VARCHAR(45) DEFAULT NULL,
  `last_name` VARCHAR(45) DEFAULT NULL,
  `full_name` VARCHAR(45) DEFAULT NULL,
  `email` VARCHAR(45) DEFAULT NULL,
  `phone` VARCHAR(45) DEFAULT NULL,
  `address_line_1` VARCHAR(45) DEFAULT NULL,
  `address_line_2` VARCHAR(45) DEFAULT NULL,
  `city` VARCHAR(45) DEFAULT NULL,
  `state` VARCHAR(45) DEFAULT NULL,
  `zip` VARCHAR(45) DEFAULT NULL,
  `title` VARCHAR(45) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE (`email`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoices` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `clientId` CHAR(36) NOT NULL,
  `client` JSON DEFAULT NULL,
  `invoiceNumber` CHAR(36) NOT NULL,
  `invoiceDate` DATE NOT NULL,
  `dueDate` DATE NOT NULL,
  `invoiceTotal` DECIMAL(10, 2) NOT NULL,
  `lineItems` JSON DEFAULT NULL,
  `status` ENUM('unpaid', 'paid', 'overdue', 'void') DEFAULT 'unpaid',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`clientId`) REFERENCES `profiles`(`id`) 
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;









